version: '3'

services:
  php:
    build: ./docker/php
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
    - ./server:/var/www
    depends_on:
      - db
    links:
      - db

  nginx:
    image: nginx
    ports:
    - 80:80
    volumes:
    - ./server:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    build: ./docker/db
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  node:
    image: node
    tty: true
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    ports:
    - 6006:6006
